name: workflow_02

on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: flashbots/suave-geth
          path: suave-geth

      - name: Mirror
        run: |
          ls suave-geth
          cp suave-geth/suave/sol/libraries/Suave.sol .
          cp suave-geth/suave/sol/libraries/SuaveForge.sol .

      - name: dispatch trigger
        run: |
          echo "repository_dispatch triggered"
