name: workflow_02

on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: flashbots/suave-geth
          path: suave-geth

      - name: Mirror
        run: |
          cp suave-geth/suave/sol/libraries/Suave.sol .
          cp suave-geth/suave/sol/libraries/SuaveForge.sol .

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
