name: workflow_02

on: [repository_dispatch, workflow_dispatch]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: flashbots/suave-geth
          path: suave-geth
          persist-credentials: false
          fetch-depth: 0

      - name: Mirror
        run: |
          cp suave-geth/suave/sol/libraries/Suave.sol .
          cp suave-geth/suave/sol/libraries/SuaveForge.sol .
          git add Suave.sol
          git add SuaveForge.sol
          rm -rf suave-geth

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit. Exiting workflow."
            exit 0
          fi

      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update Suave libs"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_SECRET }}
          branch: main
          force: true
